# airlines.py

AIRLINE_NAMES = {
    # Europe
    "LH": "Lufthansa",
    "BA": "British Airways",
    "AF": "Air France",
    "KL": "KLM",
    "LX": "SWISS",
    "SN": "Brussels Airlines",
    "OS": "Austrian Airlines",
    "SK": "Scandinavian Airlines",
    "AZ": "ITA Airways",
    "LO": "LOT Polish Airlines",
    "TP": "TAP Air Portugal",
    "IB": "Iberia",
    "VY": "Vueling",
    "U2": "easyJet",
    "FR": "Ryanair",
    "W6": "Wizz Air",
    "EI": "Aer Lingus",
    "AY": "Finnair",
    "BT": "airBaltic",
    "OK": "Czech Airlines",
    "RO": "TAROM",
    "JU": "Air Serbia",
    "FB": "Bulgaria Air",
    "HV": "Transavia",
    "DS": "easyJet Switzerland",
    "A3": "Aegean Airlines",
    "TK": "Turkish Airlines",
    "LG": "Luxair",
    "X3": "TUIfly",
    "LS": "Jet2",
    "VS": "Virgin Atlantic",

    # Middle East
    "LY": "El Al",
    "EK": "Emirates",
    "QR": "Qatar Airways",
    "EY": "Etihad Airways",
    "SV": "Saudia",
    "RJ": "Royal Jordanian",
    "WY": "Oman Air",
    "GF": "Gulf Air",
    "ME": "Middle East Airlines",

    # North America
    "AA": "American Airlines",
    "DL": "Delta Air Lines",
    "UA": "United Airlines",
    "B6": "JetBlue Airways",
    "WS": "WestJet",
    "AC": "Air Canada",
    "F9": "Frontier Airlines",
    "NK": "Spirit Airlines",
    "AS": "Alaska Airlines",
    "HA": "Hawaiian Airlines",

    # Latin America
    "LA": "LATAM Airlines",
    "AV": "Avianca",
    "AM": "Aeromexico",
    "CM": "Copa Airlines",
    "G3": "Gol Linhas Aéreas",
    "UX": "Air Europa",

    # Asia
    "SQ": "Singapore Airlines",
    "CX": "Cathay Pacific",
    "JL": "Japan Airlines",
    "NH": "ANA All Nippon Airways",
    "KE": "Korean Air",
    "OZ": "Asiana Airlines",
    "CI": "China Airlines",
    "BR": "EVA Air",
    "MU": "China Eastern Airlines",
    "CA": "Air China",
    "CZ": "China Southern Airlines",
    "HX": "Hong Kong Airlines",
    "TG": "Thai Airways",
    "VN": "Vietnam Airlines",
    "MH": "Malaysia Airlines",
    "GA": "Garuda Indonesia",
    "PR": "Philippine Airlines",
    "AI": "Air India",
    "UK": "Vistara",
    "6E": "IndiGo",
    "SG": "SpiceJet",
    "TR": "Scoot",
    "D7": "AirAsia X",
    "AK": "AirAsia",

    # Oceania
    "QF": "Qantas",
    "NZ": "Air New Zealand",
    "VA": "Virgin Australia",
    "JQ": "Jetstar",

    # Africa
    "ET": "Ethiopian Airlines",
    "KQ": "Kenya Airways",
    "MS": "EgyptAir",
    "AT": "Royal Air Maroc",
    "TU": "Tunisair",
    "SA": "South African Airways",
    "HM": "Air Seychelles",
    "WB": "RwandAir",

    # Low cost and regional
    "XR": "Corendon Airlines",
    "XQ": "SunExpress",
    "PC": "Pegasus Airlines",
}


AIRLINE_BOOKING_URLS = {
    "LH": "https://www.lufthansa.com/gb/en/flight-search",
    "BA": "https://www.britishairways.com/travel/home/public/en_gb",
    "AF": "https://wwws.airfrance.co.uk/",
    "KL": "https://www.klm.co.uk/",
    "LX": "https://www.swiss.com/gb/en/homepage",
    "SN": "https://www.brusselsairlines.com/",
    "OS": "https://www.austrian.com/",
    "SK": "https://www.flysas.com/en/",
    "AZ": "https://www.ita-airways.com/en_gb",
    "LO": "https://www.lot.com/gb/en",
    "TP": "https://www.flytap.com/en-gb/",
    "IB": "https://www.iberia.com/gb/",
    "VY": "https://www.vueling.com/en",
    "U2": "https://www.easyjet.com/en",
    "FR": "https://www.ryanair.com/gb/en",
    "W6": "https://wizzair.com/",
    "EI": "https://www.aerlingus.com/",
    "AY": "https://www.finnair.com/",
    "BT": "https://www.airbaltic.com/en/",
    "OK": "https://www.csa.cz/en/",
    "RO": "https://www.tarom.ro/en",
    "JU": "https://www.airserbia.com/en",
    "FB": "https://www.air.bg/en",
    "HV": "https://www.transavia.com/en-UK/home/",
    "DS": "https://www.easyjet.com/en",
    "A3": "https://en.aegeanair.com/",
    "TK": "https://www.turkishairlines.com/en-int/flights/",
    "LG": "https://www.luxair.lu/en",
    "X3": "https://www.tuifly.com/",
    "LS": "https://www.jet2.com/",
    "VS": "https://www.virginatlantic.com/",
    "LY": "https://www.elal.com/en/",
    "EK": "https://www.emirates.com/uk/english/",
    "QR": "https://www.qatarairways.com/en-gb/homepage.html",
    "EY": "https://www.etihad.com/en-gb/",
    "SV": "https://www.saudia.com/",
    "RJ": "https://www.rj.com/",
    "WY": "https://www.omanair.com/",
    "GF": "https://www.gulfair.com/",
    "ME": "https://www.mea.com.lb/english",
    "AA": "https://www.aa.com/",
    "DL": "https://www.delta.com/",
    "UA": "https://www.united.com/",
    "B6": "https://www.jetblue.com/",
    "WS": "https://www.westjet.com/",
    "AC": "https://www.aircanada.com/",
    "F9": "https://www.flyfrontier.com/",
    "NK": "https://www.spirit.com/",
    "AS": "https://www.alaskaair.com/",
    "HA": "https://www.hawaiianairlines.com/",
    "LA": "https://www.latamairlines.com/",
    "AV": "https://www.avianca.com/",
    "AM": "https://aeromexico.com/en-gb",
    "CM": "https://www.copaair.com/",
    "G3": "https://www.voegol.com.br/en",
    "UX": "https://www.aireuropa.com/",
    "SQ": "https://www.singaporeair.com/",
    "CX": "https://www.cathaypacific.com/",
    "JL": "https://www.jal.co.jp/jp/en/",
    "NH": "https://www.ana.co.jp/en/jp/",
    "KE": "https://www.koreanair.com/",
    "OZ": "https://flyasiana.com/",
    "CI": "https://www.china-airlines.com/",
    "BR": "https://www.evaair.com/",
    "MU": "https://www.ceair.com/",
    "CA": "https://www.airchina.com/",
    "CZ": "https://www.csair.com/",
    "HX": "https://www.hongkongairlines.com/",
    "TG": "https://www.thaiairways.com/",
    "VN": "https://www.vietnamairlines.com/",
    "MH": "https://www.malaysiaairlines.com/",
    "GA": "https://www.garuda-indonesia.com/",
    "PR": "https://www.philippineairlines.com/",
    "AI": "https://www.airindia.com/",
    "UK": "https://www.airvistara.com/",
    "6E": "https://www.goindigo.in/",
    "SG": "https://www.spicejet.com/",
    "TR": "https://www.flyscoot.com/",
    "D7": "https://www.airasia.com/",
    "AK": "https://www.airasia.com/",
    "QF": "https://www.qantas.com/",
    "NZ": "https://www.airnewzealand.co.uk/",
    "VA": "https://www.virginaustralia.com/",
    "JQ": "https://www.jetstar.com/",
    "ET": "https://www.ethiopianairlines.com/",
    "KQ": "https://www.kenya-airways.com/",
    "MS": "https://www.egyptair.com/",
    "AT": "https://www.royalairmaroc.com/",
    "TU": "https://www.tunisair.com/",
    "SA": "https://www.flysaa.com/",
    "HM": "https://www.airseychelles.com/",
    "WB": "https://www.rwandair.com/",
    "XR": "https://www.corendonairlines.com/",
    "XQ": "https://www.sunexpress.com/en/",
    "PC": "https://www.flypgs.com/en",
}
